Define API
opentracing/opentracing-lua pull request #2
Opened 2018-07-16 18:15 UTC by rnburn

This PR proposes an API for Lua. It builds off of @james-callahan's Kong API https://github.com/Kong/opentracing-lua, but removes the implementation portions that are usually put into basictracer projects (e.g. https://github.com/opentracing/basictracer-python).

The goal with the Lua API is to support these use cases:
* Working with tracers completely written in Lua (for example, Kong's Zipkin tracer https://github.com/sfhardman/kong-plugin-zipkin).
* Loading existing C++ tracers as plugins and using from Lua.
* For C++ applications that embed Lua, bridging and interoperating with the C++ tracers the application may already use.

Given the lack of direct interface support in Lua, the API isn't required as a dependency as it is with the other languages; but conforming tracers are required to implement the methods as documented.

I also wrote a [bridge-tracer](https://github.com/rnburn/lua-bridge-tracer) that implements the API and allows you to use existing C++ tracers through the dyanmic loading interface.

Cc @james-callahan, @ror6ax, @isaachier for review.

2018-07-16 18:44 UTC, isaachier commented
Wow really awesome work @rnburn! I am glad to see someone did this work for Lua. Maybe this effort will prove worthwhile in other languages as well.

2018-07-17 03:11 UTC, james-callahan requested changes
Thanks for putting in the work!

Yet I'm not sure what the use of all this is (due to lua not needing "interfaces"):
  - is it a template project for others starting opentracing implementations?
  - should it act as a "base class" somehow?

2018-07-17 03:11 UTC, james-callahan commented on opentracing/span.lua
> +  new = new
add semicolon?

2018-07-17 03:11 UTC, james-callahan commented on opentracing/span_context.lua
> +  return setmetatable({
Mixed tabs and spaces.

2018-07-17 03:24 UTC, rnburn commented
@james-callahan - it's only serving as documentation and as a specification for what methods a conforming OT Lua tracers need to implement.

I don't think it needs to provide anything that's used directly; though at some point it might make sense to add in a mocktracer and these [constants](https://github.com/opentracing/opentracing-python/blob/master/opentracing/ext/tags.py) that are usually defined.

2018-07-17 20:01 UTC, rnburn commented on opentracing/span.lua
> +  new = new
Added.

2018-07-17 20:01 UTC, rnburn commented on opentracing/span_context.lua
> +  return setmetatable({
Fixed.

2018-07-18 02:54 UTC, james-callahan commented
Looks good now; if you want to squash down your commits to remove intermediary fixes I can merge.

2018-07-18 02:54 UTC, james-callahan approved these changes

2018-07-20 04:09 UTC, rnburn commented
@james-callahan - I set up the repo to squash on merge (the default for the other opentracing languages).

Let's keep it open a little longer. I'm going to post it on the OT gitter channels to see if anyone has more feedback.

2018-07-20 04:14 UTC, james-callahan commented
> @james-callahan - I set up the repo to squash on merge (the default for the other opentracing languages).

:( I really hate squash-on-merging. it breaks commit signing, in addition to making it hard to pull apart large pull requests. At least it doesn't appear to be the default.

> Let's keep it open a little longer. I'm going to post it on the OT gitter channels to see if anyone has more feedback.

I feel like for starting a project it's better to have *something* and have people file PRs to fix it rather than for feedback on the initial implementation.
I'm happy for it to be merged as-is.

2018-07-23 18:00 UTC, tedsuo commented
Hi @james-callahan and @rnburn, I'm going to merge this since commentary has died down.

To explain the squash-and-merge philosophy: for API repos, we want master to have a clean commit history, where every commit on master to represents a usable version. Otherwise, there's a risk that a user could land on something broken, or ideas that we tried and then backed away from. But we don't want to require all intermediary commits on a PR branch to have this requirement. Hence squash-and-merge. As long as the squashed commits are linked to the original PRs, the git history remains for someone who wants to investigate the details. Not perfect but that's the reasoning. We should become even stricter about our process as the APIs mature and become stable.

For early, unstable versions like this, I think we should move fast to merge changes into master, we shouldn't build up a giant pile of changes on a single PR.

2018-07-23 18:02 UTC, tedsuo commented
@rnburn btw I noticed there was no version number yet. Can we do SEMVER and start this as `v0.1`? I'll merge once that's added.

2018-07-23 18:20 UTC, rnburn commented
I set `_VERSION = '0.1.0'`

2018-07-23 18:28 UTC, isaachier commented
Isn't there a canonical way to set `_VERSION`? Does luarocks provide the version from the rockspec to users?

Edit: Clarify

2018-07-23 18:30 UTC, isaachier commented
Actually never mind. Looks like some packages do supply it in both the rockspec and the lua source. See [here](https://github.com/craigbarnes/lua-gumbo/blob/master/gumbo.lua#L94) for an example.

2018-07-23 20:34 UTC, tedsuo commented
LGTM. Seems like there's a smear of versioning approaches in Lua. @isaachier we can always refactor how we are exposing/versioning.

2018-07-23 20:35 UTC, merged

2018-07-24 00:33 UTC, daurnimator commented
> we want master to have a clean commit history, where every commit on master to represents a usable version.

I entirely agree. But I think it should always be up to the pull-request author to make that clean history, never the reviewer/merger.

> But we don't want to require all intermediary commits on a PR branch to have this requirement.

There should never be intermediary commits in a PR; the author should amend them as they improve the PR.

2018-07-24 00:33 UTC, james-callahan commented
> we want master to have a clean commit history, where every commit on master to represents a usable version.

I entirely agree. But I think it should always be up to the pull-request author to make that clean history, never the reviewer/merger.

> But we don't want to require all intermediary commits on a PR branch to have this requirement.

There should never be intermediary commits in a PR; the author should amend them as they improve the PR.

2019-01-04 17:14 UTC, yurishkuro commented
>  The author should amend them as they improve the PR.

This only creates unnecessary friction, for both maintainers and contributors. I almost never encounter a situation where it's imperative that commits in the PR must be preserved in master - in most cases it's just a sign that the PR is doing too many things and should be split.